frr version 10.5.1_git
frr defaults traditional
hostname rr
log syslog informational
hostname evpn-rr
service integrated-vtysh-config
!
router bgp 65512
 bgp router-id 192.168.188.152
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor local peer-group
 neighbor local remote-as 65512
 neighbor rosa peer-group
 neighbor rosa remote-as 65512
 bgp listen range 192.168.188.0/24 peer-group local
 bgp listen range 10.0.0.0/8 peer-group rosa
 !
 address-family ipv4 unicast
  neighbor local activate
  neighbor local route-reflector-client
  neighbor rosa activate
  neighbor rosa route-reflector-client
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor local activate
  neighbor local route-reflector-client
  neighbor rosa activate
  neighbor rosa route-reflector-client
 exit-address-family
exit
!
