apiVersion: k8s.ovn.org/v1
kind: RouteAdvertisements
metadata:
  name: evpn-on-prem-routeadvertisement
spec:
  targetVRF: auto
  advertisements:
    - PodNetwork
  nodeSelector: {}
  frrConfigurationSelector:
    matchLabels:
      evpn-peering: "on-prem"
  networkSelectors:
    - networkSelectionType: ClusterUserDefinedNetworks
      clusterUserDefinedNetworkSelector:
        networkSelector:
          matchLabels:
            network: "evpn-on-prem"